/* This file is autogenerated by gen/prop/bool-props; DO NOT EDIT. */

#include "__bsearch.h"
#include "bitset.h"
#include "rune.h"
#include "unicode/prop.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup[] = {
	{RUNE_C(0x002FF0), RUNE_C(0x002FF1)},
	{RUNE_C(0x002FF4), RUNE_C(0x002FFD)},
	{RUNE_C(0x0031EF), RUNE_C(0x0031EF)},
};

__MLIB_DEFINE_BSEARCH_CONTAINS(lookup)

bool
uprop_is_idsb(rune ch)
{
	return mlib_lookup_contains(ch);
}
