/* This file is autogenerated by gen/prop/stc; DO NOT EDIT. */

#include "__bsearch.h"
#include "macros.h"
#include "rune.h"
#include "unicode/prop.h"

static const struct {
	rune k, v;
} lookup[] = {
	{RUNE_C(0x0001C4), RUNE_C(0x0001C5)},
	{RUNE_C(0x0001C6), RUNE_C(0x0001C5)},
	{RUNE_C(0x0001C7), RUNE_C(0x0001C8)},
	{RUNE_C(0x0001C9), RUNE_C(0x0001C8)},
	{RUNE_C(0x0001CA), RUNE_C(0x0001CB)},
	{RUNE_C(0x0001CC), RUNE_C(0x0001CB)},
	{RUNE_C(0x0001F1), RUNE_C(0x0001F2)},
	{RUNE_C(0x0001F3), RUNE_C(0x0001F2)},
};

__MLIB_DEFINE_BSEARCH_KV(rune, lookup, uprop_get_suc(ch))

rune
uprop_get_stc(rune ch)
{
	return mlib_lookup_kv(ch);
}
