/* This file is autogenerated by gen/prop/bool-props; DO NOT EDIT. */

#include "__bsearch.h"
#include "bitset.h"
#include "rune.h"
#include "unicode/prop.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup[] = {
	{RUNE_C(0x01F3FB), RUNE_C(0x01F3FF)},
};

__MLIB_DEFINE_BSEARCH_CONTAINS(lookup)

bool
uprop_is_emod(rune ch)
{
	return mlib_lookup_contains(ch);
}
