/* This file is autogenerated by gen/prop/bool-props; DO NOT EDIT. */

#include "_bsearch.h"
#include "bitset.h"
#include "rune.h"
#include "unicode/prop.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup[] = {
	{RUNE_C(0x003006), RUNE_C(0x003007)},
	{RUNE_C(0x003021), RUNE_C(0x003029)},
	{RUNE_C(0x003038), RUNE_C(0x00303A)},
	{RUNE_C(0x003400), RUNE_C(0x004DBF)},
	{RUNE_C(0x004E00), RUNE_C(0x009FFF)},
	{RUNE_C(0x00F900), RUNE_C(0x00FA6D)},
	{RUNE_C(0x00FA70), RUNE_C(0x00FAD9)},
	{RUNE_C(0x016FE4), RUNE_C(0x016FE4)},
	{RUNE_C(0x017000), RUNE_C(0x0187F7)},
	{RUNE_C(0x018800), RUNE_C(0x018CD5)},
	{RUNE_C(0x018D00), RUNE_C(0x018D08)},
	{RUNE_C(0x01B170), RUNE_C(0x01B2FB)},
	{RUNE_C(0x020000), RUNE_C(0x02A6DF)},
	{RUNE_C(0x02A700), RUNE_C(0x02B739)},
	{RUNE_C(0x02B740), RUNE_C(0x02B81D)},
	{RUNE_C(0x02B820), RUNE_C(0x02CEA1)},
	{RUNE_C(0x02CEB0), RUNE_C(0x02EBE0)},
	{RUNE_C(0x02EBF0), RUNE_C(0x02EE5D)},
	{RUNE_C(0x02F800), RUNE_C(0x02FA1D)},
	{RUNE_C(0x030000), RUNE_C(0x03134A)},
	{RUNE_C(0x031350), RUNE_C(0x0323AF)},
};

_MLIB_DEFINE_BSEARCH_CONTAINS(lookup)

bool
uprop_is_ideo(rune ch)
{
	return mlib_lookup_contains(ch);
}
