/* This file is autogenerated by gen/prop/bool-props; DO NOT EDIT. */

#include "__bsearch.h"
#include "bitset.h"
#include "rune.h"
#include "unicode/prop.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup[] = {
	{RUNE_C(0x002202), RUNE_C(0x002202)},
	{RUNE_C(0x002207), RUNE_C(0x002207)},
	{RUNE_C(0x00221E), RUNE_C(0x00221E)},
	{RUNE_C(0x01D6C1), RUNE_C(0x01D6C1)},
	{RUNE_C(0x01D6DB), RUNE_C(0x01D6DB)},
	{RUNE_C(0x01D6FB), RUNE_C(0x01D6FB)},
	{RUNE_C(0x01D715), RUNE_C(0x01D715)},
	{RUNE_C(0x01D735), RUNE_C(0x01D735)},
	{RUNE_C(0x01D74F), RUNE_C(0x01D74F)},
	{RUNE_C(0x01D76F), RUNE_C(0x01D76F)},
	{RUNE_C(0x01D789), RUNE_C(0x01D789)},
	{RUNE_C(0x01D7A9), RUNE_C(0x01D7A9)},
	{RUNE_C(0x01D7C3), RUNE_C(0x01D7C3)},
};

__MLIB_DEFINE_BSEARCH_CONTAINS(lookup)

bool
uprop_is_id_compat_math_start(rune ch)
{
	return mlib_lookup_contains(ch);
}
