/* This file is autogenerated by gen/prop/bool-props; DO NOT EDIT. */

#include "__bsearch.h"
#include "bitset.h"
#include "rune.h"
#include "unicode/prop.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup[] = {
	{RUNE_C(0x00180B), RUNE_C(0x00180D)},
	{RUNE_C(0x00180F), RUNE_C(0x00180F)},
	{RUNE_C(0x00FE00), RUNE_C(0x00FE0F)},
	{RUNE_C(0x0E0100), RUNE_C(0x0E01EF)},
};

__MLIB_DEFINE_BSEARCH_CONTAINS(lookup)

bool
uprop_is_vs(rune ch)
{
	return mlib_lookup_contains(ch);
}
