/* This file is autogenerated by gen/prop/bool-props; DO NOT EDIT. */

#include "_bsearch.h"
#include "bitset.h"
#include "rune.h"
#include "unicode/prop.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup[] = {
	{RUNE_C(0x000149), RUNE_C(0x000149)},
	{RUNE_C(0x000673), RUNE_C(0x000673)},
	{RUNE_C(0x000F77), RUNE_C(0x000F77)},
	{RUNE_C(0x000F79), RUNE_C(0x000F79)},
	{RUNE_C(0x0017A3), RUNE_C(0x0017A4)},
	{RUNE_C(0x00206A), RUNE_C(0x00206F)},
	{RUNE_C(0x002329), RUNE_C(0x00232A)},
	{RUNE_C(0x0E0001), RUNE_C(0x0E0001)},
};

_MLIB_DEFINE_BSEARCH_CONTAINS(lookup)

bool
uprop_is_dep(rune ch)
{
	return mlib_lookup_contains(ch);
}
