/* This file is autogenerated by gen/prop/bool-props; DO NOT EDIT. */

#include "_bsearch.h"
#include "bitset.h"
#include "rune.h"
#include "unicode/prop.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup[] = {
	{RUNE_C(0x002E80), RUNE_C(0x002E99)},
	{RUNE_C(0x002E9B), RUNE_C(0x002EF3)},
	{RUNE_C(0x002F00), RUNE_C(0x002FD5)},
};

_MLIB_DEFINE_BSEARCH_CONTAINS(lookup)

bool
uprop_is_radical(rune ch)
{
	return mlib_lookup_contains(ch);
}
