/* This file is autogenerated by gen/prop/bool-props; DO NOT EDIT. */

#include "_bsearch.h"
#include "bitset.h"
#include "rune.h"
#include "unicode/prop.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup[] = {
	{RUNE_C(0x000E40), RUNE_C(0x000E44)},
	{RUNE_C(0x000EC0), RUNE_C(0x000EC4)},
	{RUNE_C(0x0019B5), RUNE_C(0x0019B7)},
	{RUNE_C(0x0019BA), RUNE_C(0x0019BA)},
	{RUNE_C(0x00AAB5), RUNE_C(0x00AAB6)},
	{RUNE_C(0x00AAB9), RUNE_C(0x00AAB9)},
	{RUNE_C(0x00AABB), RUNE_C(0x00AABC)},
};

_MLIB_DEFINE_BSEARCH_CONTAINS(lookup)

bool
uprop_is_loe(rune ch)
{
	return mlib_lookup_contains(ch);
}
